export const FETCH_SHOWINGS = "FETCH_SHOWINGS";
export const FETCH_SHOWINGS_SUCCESS = "FETCH_SHOWINGS_SUCCESS";
export const FETCH_SHOWINGS_FAIL = "FETCH_SHOWINGS_FAIL";

export const ADD_SHOWING = "ADD_SHOWING";
export const ADD_SHOWING_SUCCESS = "ADD_SHOWING_SUCCESS";
export const ADD_SHOWING_FAIL = "ADD_SHOWING_FAIL";
